% 2016-3-16 Edited by Brian (Generated by MATLAB)
function [TimeSec,Work,VO2,VO2kg,VCO2,RQ,VEBTPS,RR,HT,RestLevel] = importMetabolicCartData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMESEC,WORK,VO2,VO2KG,VCO2,RQ,VEBTPS,RR,HT,RESTLEVEL] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [TIMESEC,WORK,VO2,VO2KG,VCO2,RQ,VEBTPS,RR,HT,RESTLEVEL] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [TimeSec,Work,VO2,VO2kg,VCO2,RQ,VEBTPS,RR,HT,RestLevel] =
%   importfile('EXO99-112016-v2-js.txt');
%
%   OR
%
%   [TimeSec,Work,VO2,VO2kg,VCO2,RQ,VEBTPS,RR,HT,RestLevel] =
%   importfile('EXO99-112016-v2-js.txt',8, 1341);
%
%    See also TEXTSCAN.

%% Initialize variables.
if nargin<=2
    startRow = 8;
    endRow   = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%8s%8s%8s%8s%8s%8s%8s%8s%8s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8]);
rawCellColumns = raw(:, [1,9,10]);


%% Exclude rows with non-numeric cells
J = ~all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),rawNumericColumns),2); % Find rows with non-numeric cells
rawNumericColumns(J,:) = [];
rawCellColumns(J,:) = [];

%% Allocate imported array to column variable names
TimeSec   = rawCellColumns(:, 1);
Work      = cell2mat(rawNumericColumns(:, 1));
VO2       = cell2mat(rawNumericColumns(:, 2));
VO2kg     = cell2mat(rawNumericColumns(:, 3));
VCO2      = cell2mat(rawNumericColumns(:, 4));
RQ        = cell2mat(rawNumericColumns(:, 5));
VEBTPS    = cell2mat(rawNumericColumns(:, 6));
RR        = cell2mat(rawNumericColumns(:, 7));
HT        = rawCellColumns(:, 2);
RestLevel = rawCellColumns(:, 3);

