function pocketnirslog = importNIRSdata(filename,startRow,endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   POCKETNIRSLOG2015022311 = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   POCKETNIRSLOG2015022311 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   pocketnirslog2015022311 =
%   importfile('pocket_nirs_log_20150223_11.54.02.Marshall1002SM_CH1.left_CH2.right_WR20.PNI',
%   5, 27824);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/03/08 21:16:01

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
pocketnirslog = dataset(dataArray{1:end-1}, 'VarNames', {'ElapsedCnt','DateTime','ElapsedTime','Event','ExtTrgEvent','ZeroSet','CH1_PRbpm','CH1_BFau','CH1_oxyHbau','CH1_deoxyHbau','CH1_totalHbau','CH1_735nm','CH1_810nm','CH1_850nm','CH1_DARK','CH2_PRbpm','CH2_BFau','CH2_oxyHbau','CH2_deoxyHbau','CH2_totalHbau','CH2_735nm','CH2_810nm','CH2_850nm','CH2_DARK'});
